
on: [push, pull_request]
name: Python Linting
jobs:
  PythonLinting:
    name: Python linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "api core"
          use-pylint: true
          use-pycodestyle: true
          use-flake8: true
          use-black: false
          use-mypy: true
          use-isort: false
          extra-pylint-options: ""
          extra-pycodestyle-options: ""
          extra-flake8-options: ""
          extra-black-options: ""
          extra-mypy-options: ""
          extra-isort-options: ""

