name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    defaults:
      run:
        working-directory: web
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'dhonus'
        reponame: 'bc-prace'
        token: ${{ secrets.GITHUB_TOKEN }}
